matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - bash release_scripts/ci.sh

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

after_success:
  - codecov --disable=gcov

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

dist: focal

node_js:
  - 10.22.0
